# Generated by Django 4.2.2 on 2023-06-07 15:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.user',),
        ),
        migrations.CreateModel(
            name='TherapistAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=10, null=True)),
                ('hoursPerWeek', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None)),
                ('technique', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None)),
                ('describeYourSelf', models.CharField(blank=True, max_length=10, null=True)),
                ('fluency', models.CharField(blank=True, max_length=10, null=True)),
                ('chat2to3TimesADay', models.CharField(blank=True, max_length=10, null=True)),
                ('sessionPreferredTime', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.CharField(blank=True, max_length=100, null=True)),
                ('therapist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
    ]
