# Generated by Django 4.2.2 on 2023-06-07 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_alter_therapistadditionaldetails_describeyourself_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistadditionaldetails',
            name='fluency',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None),
        ),
    ]
