# Generated by Django 4.2.2 on 2023-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_alter_therapistadditionaldetails_fluency'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistadditionaldetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-process', 'On Process'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
