# Generated by Django 4.2.2 on 2023-06-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_therapistadditionaldetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapist.therapist')),
            ],
        ),
    ]
