# Generated by Django 4.2.2 on 2023-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_therapistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistavailability',
            name='session_booked',
            field=models.BooleanField(default=False),
        ),
    ]
