# Generated by Django 4.2.2 on 2023-06-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_therapistadditionaldetails_status'),
        ('client', '0002_clientadditionaldetails_subscription_and_more'),
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_sessions_as_client', to='client.client')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_sessions_as_therapist', to='therapist.therapist')),
            ],
        ),
    ]
