# Generated by Django 4.2.2 on 2023-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_therapysessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TherapySessions',
        ),
    ]
