# Generated by Django 4.2.2 on 2023-06-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_therapysessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='therapy_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.therapysessions'),
        ),
    ]
