# Generated by Django 4.2.2 on 2023-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_user_therapy_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('onreview', 'On Review'), ('approved', 'Approved')], max_length=255, null=True),
        ),
    ]
