# Generated by Django 4.2.2 on 2023-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
