# Generated by Django 4.2.2 on 2023-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysessions',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
