# Generated by Django 4.2.2 on 2023-06-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_therapysessions_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapysessions',
            old_name='cancelled',
            new_name='cancelled_by_therapist',
        ),
    ]
